### ISSUE TITLE
Pull Request Interest?

### ISSUE THREAD

**Issue by CanOfBees** [timathom/simple-statsxq#1]
Hi Tim - 
I have some work that... well, if I don't share it with you now, I'll never share it. Would you be interested in a PR? If you are, would you prefer to have it applied to your development branch or master?

The work is relatively minimal and might require a bit of touch-up. Let me know if you'd like to proceed.
Thanks,
Bridger

**Comment by timathom** [comment]
Hi, Bridger--absolutely, your contributions are always welcome. I haven't been able to work on this project recently, but please feel free to open the PR on the development branch.

**Comment by CanOfBees** [comment]
Tim - hi and thanks. I'll get a PR worked up shortly after the holiday.
Best,
Bridger
